import React from 'react';
import SidebarMenu from '../sidebar/Sidebar';
import Logo from '../Logo';

import { useApp } from '../../contexts/app';
import { propReactElement, propUser } from '../../propTypes';

export default function AppLayout({ children, user }) {
  const { setIsSidebarOpen } = useApp();

  return (
    <div className="flex flex-row min-h-screen h-screen  bg-gray-100 text-gray-800">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <SidebarMenu />
      <main className="main flex flex-col flex-grow -ml-[300px] md:ml-0 transition-all duration-150 ease-in w-full overflow-auto">
        <header className="header bg-white shadow py-4 px-4">
          <div className="header-content flex items-center flex-row">
            <div className="flex md:hidden">
              <button type="button" className="flex items-center justify-center h-10 w-10 border-transparent mr-4" onClick={() => { setIsSidebarOpen(true); }}>
                <svg
                  className="h-6 w-6 text-budget-purple-700 "
                  fill="#442776"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  viewBox="0 0 44 54"
                  stroke="currentColor"
                >
                  <path d="M 5 8 A 2.0002 2.0002 0 1 0 5 12 L 45 12 A 2.0002 2.0002 0 1 0 45 8 L 5 8 z M 5 23 A 2.0002 2.0002 0 1 0 5 27 L 45 27 A 2.0002 2.0002 0 1 0 45 23 L 5 23 z M 5 38 A 2.0002 2.0002 0 1 0 5 42 L 45 42 A 2.0002 2.0002 0 1 0 45 38 L 5 38 z" />
                </svg>
              </button>
            </div>
            <Logo />
            <div className="self-end">
              {user && user?.picture && (
              <img
                src={user?.picture}
                alt="avatar"
                height={36}
                width={36}
                className="h-10 w-10 bg-gray-200 border rounded-full"
              />
              )}
            </div>
          </div>
        </header>
        <div className="main-content flex flex-col flex-1 p-4">
          { children}
        </div>
        <footer className="footer px-4 py-6">
          <div className="footer-content">
            <p className="text-sm text-gray-600 text-center">
              © EasyBudget 2021. All rights reserved.
              {' '}
              <a href="https://twitter.com/iaminos">by Yohendry</a>
            </p>
          </div>
        </footer>
      </main>

    </div>
  );
}

AppLayout.propTypes = {
  children: propReactElement.isRequired,
  user: propUser.isRequired,
};
